# Generated by Django 5.1.7 on 2025-03-09 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="image",
        ),
        migrations.AddField(
            model_name="destination",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="destination",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
