# Generated by Django 5.1.7 on 2025-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0002_remove_destination_image_destination_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouristSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="tourist_spots/")),
            ],
        ),
        migrations.RemoveField(
            model_name="destination",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="location",
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(default="unknown", upload_to="destinations/"),
            preserve_default=False,
        ),
    ]
