# Generated by Django 5.1.7 on 2025-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0003_touristspot_remove_destination_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristspot",
            old_name="image",
            new_name="image1",
        ),
        migrations.RenameField(
            model_name="touristspot",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="touristspot",
            name="activities",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="touristspot",
            name="cultural_significance",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="touristspot",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="tourist_spots/"),
        ),
        migrations.AddField(
            model_name="touristspot",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="tourist_spots/"),
        ),
        migrations.AddField(
            model_name="touristspot",
            name="travel_tips",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
    ]
