# Generated by Django 5.1.7 on 2025-03-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0004_rename_image_touristspot_image1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThrillingAdventure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="thrilling_adventures/")),
                ("description", models.TextField()),
                ("highlights", models.TextField()),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adventures",
                        to="tourism.touristspot",
                    ),
                ),
            ],
        ),
    ]
