# Generated by Django 5.1.7 on 2025-03-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0005_thrillingadventure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thrillingadventure",
            name="image",
        ),
        migrations.CreateModel(
            name="ThrillingAdventureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="thrilling_adventures/")),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tourism.thrillingadventure",
                    ),
                ),
            ],
        ),
    ]
