# Generated by Django 5.1.7 on 2025-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0006_remove_thrillingadventure_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thrillingadventure",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="thrilling_adventures/"
            ),
        ),
        migrations.AddField(
            model_name="thrillingadventure",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="thrilling_adventures/"
            ),
        ),
        migrations.AddField(
            model_name="thrillingadventure",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="thrilling_adventures/"
            ),
        ),
        migrations.AlterField(
            model_name="thrillingadventure",
            name="spot",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="thrillingadventure",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="ThrillingAdventureImage",
        ),
    ]
