# Generated by Django 5.1.7 on 2025-03-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tourism",
            "0007_thrillingadventure_image1_thrillingadventure_image2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thrillingadventure",
            name="spot",
        ),
    ]
