# Generated by Django 5.1.7 on 2025-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0008_remove_thrillingadventure_spot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="thrilling_adventures/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="thrilling_adventures/"
                    ),
                ),
                ("highlights1", models.TextField()),
                ("highlights2", models.TextField()),
            ],
        ),
    ]
