# Generated by Django 5.1.7 on 2025-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0010_delicacies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.TextField()),
                ("image1", models.ImageField(blank=True, null=True, upload_to="stay/")),
            ],
        ),
    ]
