# Generated by Django 5.1.7 on 2025-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0012_dining"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="Nature/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="Nature/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="Nature/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="Nature/"),
                ),
            ],
        ),
    ]
