# Generated by Django 5.1.7 on 2025-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0013_nature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nature",
            name="image4",
        ),
        migrations.AddField(
            model_name="nature",
            name="highlights",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
    ]
